messages:
  join: '%player% &a&lhas joined the server!'
  leave: '%player% &c&lhas left the server!'
chat:
  format: '&r%channel_prefix%&r<%player%&r>: %msg%'
  broadcast: '&c[Broadcast] '
  pm:
    prefix: '&f[&6PM&f]'
    from: '%pm_prefix% &7From &r%player%&7:&r %msg%'
    to: '%pm_prefix% &7To &r%player%&7:&r %msg%'
    sound:
      effect: ENTITY_ITEM_PICKUP
      v: 1
      v1: 1
whitelist:
  enabled: true
  message: '&cSorry but you are not allowed to play here, to apply go to discord (invite.gg/genrealms).'
  white-listed:
    - 4cb7aa21-96ba-4237-9469-56a43a781bb6
