name: SMP-Core
version: ${project.version}
main: me.prodigy4532.smpcore.SMP
api-version: 1.14
authors: [BGMP, Prodigy4532]
depend: [LuckPerms]
description: SMPCommand Core for Gen Reamls
website: genrealms.net