main: com.braeh.core.SERVER
version: 1.0.0
name: SERVER
author: Prodigy4532
commands:
  maintenance:
    description: ServerMaintenance Commands!
  sm:
    description: ServerMaintenance Commands!
  m:
    description: ServerMaintenance Commands!
  servermaintenance:
    description: ServerMaintenance Commands!
  ma:
      description: ServerMaintenance Commands!